Depurando script's

diff --git a/trunk/beta/bin/emaku-server b/trunk/beta/bin/emaku-server
--- a/trunk/beta/bin/emaku-server
+++ b/trunk/beta/bin/emaku-server
@@ -155,16 +155,16 @@ verify() {
       exit 1
     fi
 
-    if [ ! -r $JMIDAS_HOME/conf ] ; then
-      echo
-      echo "ERROR: El usuario \"$USER\" no posee privilegios suficientes"
-      echo "       para iniciar el servidor E-Maku."
-      echo "---"
-      echo " Por defecto, el usuario autorizado para iniciar este servicio"
-      echo " es el \"root\"."
-      echo "---"
-      exit 1
-    fi
+    #if [ ! -r $JMIDAS_HOME/conf ] ; then
+    #  echo
+    #  echo "ERROR: El usuario \"$USER\" no posee privilegios suficientes"
+    #  echo "       para iniciar el servidor E-Maku."
+    #  echo "---"
+    #  echo " Por defecto, el usuario autorizado para iniciar este servicio"
+    #  echo " es el \"root\"."
+    #  echo "---"
+    #  exit 1
+    #fi
 
 }
 
